export default {
  // address
  zipCode: "address.zipCode",
  zipCodeByState: "address.zipCodeByState",
  city: "address.city",
  cityPrefix: "address.cityPrefix",
  citySuffix: "address.citySuffix",
  streetName: "address.streetName",
  streetAddress: "address.streetAddress",
  streetSuffix: "address.streetSuffix",
  streetPrefix: "address.streetPrefix",
  secondaryAddress: "address.secondaryAddress",
  county: "address.county",
  country: "address.country",
  countryCode: "address.countryCode",
  state: "address.state",
  stateAbbr: "address.stateAbbr",
  latitude: "address.latitude",
  longitude: "address.longitude",
  direction: "address.direction",
  cardinalDirection: "address.cardinalDirection",
  ordinalDirection: "address.ordinalDirection",
  nearbyGPSCoordinate: "address.nearbyGPSCoordinate",
  timeZone: "address.timeZone",
};
